| Soil_Type | Season | Crop      | Recommendation_Score |
| --------- | ------ | --------- | -------------------- |
| Loamy     | Kharif | Rice      | 95                   |
| Loamy     | Rabi   | Wheat     | 90                   |
| Sandy     | Kharif | Maize     | 85                   |
| Sandy     | Rabi   | Barley    | 80                   |
| Clay      | Kharif | Cotton    | 88                   |
| Clay      | Rabi   | Pulses    | 83                   |
| Loamy     | Kharif | Sugarcane | 92                   |
| Sandy     | Kharif | Sorghum   | 78                   |
| Clay      | Rabi   | Soybean   | 81                   |
| Loamy     | Rabi   | Mustard   | 87                   |
